### ISSUE TITLE
Battlenet Wine Preloader Crash/ Error Code 136

### ISSUE THREAD

**Issue by Gustavo17pacheco** [lutris/docs#146]
Been trying to install Overwatch 2 but wine-preloader crashes everytime and I get error code 136.

This is the full log:

Started initial process 2531 from /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runtime/winetricks/winetricks --unattended arial
Start monitoring process.
------------------------------------------------------
warning: You are running winetricks-20220411-next, latest upstream is winetricks-20230212!
------------------------------------------------------
------------------------------------------------------
warning: You should update using your distribution's package manager, --self-update, or manually.
------------------------------------------------------
------------------------------------------------------
warning: Your version of wine 4.11-31860-gfc7b4bc5528 is no longer supported upstream. You should upgrade to 5.x
------------------------------------------------------
Executing mkdir -p /mnt/Games/Games
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20220411-next - sha256sum: 50b745d7f46ead56fd0c9e6d753d53ea0ae368c988434c25d65fec66307e5d4f with wine-4.11-31860-gfc7b4bc5528 (Staging) and WINEARCH=win64
Executing w_do_call arial
Executing mkdir -p /mnt/Games/Games
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_arial 
grep: warning: stray \ before /
grep: warning: stray \ before /
Executing cabextract -q -d /mnt/Games/Games/battlenet/dosdevices/c:/windows/temp /home/gustavo/.var/app/net.lutris.Lutris/cache/winetricks/corefonts/arial32.exe
------------------------------------------------------
warning: Running /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wineserver -w. This will hang until all wine processes in prefix=/mnt/Games/Games/battlenet terminate
------------------------------------------------------
Executing /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine regedit /S C:\windows\Temp\_register-font.reg
fsync: up and running.
Executing /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine64 regedit /S C:\windows\Temp\_register-font.reg
Executing cp /mnt/Games/Games/battlenet/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.IO3VjbCk/_reg_304f5183_2531.reg
Executing /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine regedit /S C:\windows\Temp\_register-font.reg
Executing /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine64 regedit /S C:\windows\Temp\_register-font.reg
Executing cp /mnt/Games/Games/battlenet/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.IO3VjbCk/_reg_964415d4_2531.reg
Executing /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine regedit /S C:\windows\Temp\_register-font.reg
Executing /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine64 regedit /S C:\windows\Temp\_register-font.reg
Executing cp /mnt/Games/Games/battlenet/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.IO3VjbCk/_reg_1f616c49_2531.reg
Executing /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine regedit /S C:\windows\Temp\_register-font.reg
Executing /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine64 regedit /S C:\windows\Temp\_register-font.reg
Executing cp /mnt/Games/Games/battlenet/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.IO3VjbCk/_reg_16f0ad00_2531.reg
Executing /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine regedit /S C:\windows\Temp\_register-font.reg
Executing /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine64 regedit /S C:\windows\Temp\_register-font.reg
Executing cp /mnt/Games/Games/battlenet/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.IO3VjbCk/_reg_afb17c0c_2531.reg
Executing /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine regedit /S C:\windows\Temp\_register-font.reg
Executing /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine64 regedit /S C:\windows\Temp\_register-font.reg
Executing cp /mnt/Games/Games/battlenet/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.IO3VjbCk/_reg_4cd1fddd_2531.reg
Executing /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine regedit /S C:\windows\Temp\_register-font.reg
Executing /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine64 regedit /S C:\windows\Temp\_register-font.reg
Executing cp /mnt/Games/Games/battlenet/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.IO3VjbCk/_reg_dae52f18_2531.reg
Executing /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine regedit /S C:\windows\Temp\_register-font.reg
Executing /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine64 regedit /S C:\windows\Temp\_register-font.reg
Executing cp /mnt/Games/Games/battlenet/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.IO3VjbCk/_reg_f89c822c_2531.reg
Executing cabextract -q -d /mnt/Games/Games/battlenet/dosdevices/c:/windows/temp /home/gustavo/.var/app/net.lutris.Lutris/cache/winetricks/corefonts/arialb32.exe
------------------------------------------------------
warning: Running /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wineserver -w. This will hang until all wine processes in prefix=/mnt/Games/Games/battlenet terminate
------------------------------------------------------
Executing /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine regedit /S C:\windows\Temp\_register-font.reg
fsync: up and running.
Executing /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine64 regedit /S C:\windows\Temp\_register-font.reg
Executing cp /mnt/Games/Games/battlenet/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.IO3VjbCk/_reg_66d0267b_2531.reg
Executing /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine regedit /S C:\windows\Temp\_register-font.reg
Executing /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine64 regedit /S C:\windows\Temp\_register-font.reg
Executing cp /mnt/Games/Games/battlenet/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.IO3VjbCk/_reg_8067e78b_2531.reg
You opted in, so reporting 'arial ' to the winetricks maintainer so he knows which winetricks verbs get used and which don't.  Use --optout to disable future reports.
Monitored process exited.
Initial process has exited (return code: 0)
Exit with return code 0
Started initial process 3779 from /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runtime/winetricks/winetricks --unattended tahoma
Start monitoring process.
------------------------------------------------------
warning: You are running winetricks-20220411-next, latest upstream is winetricks-20230212!
------------------------------------------------------
------------------------------------------------------
warning: You should update using your distribution's package manager, --self-update, or manually.
------------------------------------------------------
------------------------------------------------------
warning: Your version of wine 4.11-31860-gfc7b4bc5528 is no longer supported upstream. You should upgrade to 5.x
------------------------------------------------------
Executing mkdir -p /mnt/Games/Games
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20220411-next - sha256sum: 50b745d7f46ead56fd0c9e6d753d53ea0ae368c988434c25d65fec66307e5d4f with wine-4.11-31860-gfc7b4bc5528 (Staging) and WINEARCH=win64
Executing w_do_call tahoma
Executing mkdir -p /mnt/Games/Games
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_tahoma 
grep: warning: stray \ before /
Executing cabextract -q -d /mnt/Games/Games/battlenet/dosdevices/c:/windows/temp /home/gustavo/.var/app/net.lutris.Lutris/cache/winetricks/tahoma/IELPKTH.CAB
/home/gustavo/.var/app/net.lutris.Lutris/cache/winetricks/tahoma/IELPKTH.CAB: WARNING; possible 5592 extra bytes at end of file.
------------------------------------------------------
warning: Running /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wineserver -w. This will hang until all wine processes in prefix=/mnt/Games/Games/battlenet terminate
------------------------------------------------------
Executing /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine regedit /S C:\windows\Temp\_register-font.reg
fsync: up and running.
Executing /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine64 regedit /S C:\windows\Temp\_register-font.reg
Executing cp /mnt/Games/Games/battlenet/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.IMd7VHlL/_reg_a6378261_3779.reg
Executing /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine regedit /S C:\windows\Temp\_register-font.reg
Executing /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine64 regedit /S C:\windows\Temp\_register-font.reg
Executing cp /mnt/Games/Games/battlenet/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.IMd7VHlL/_reg_2381d506_3779.reg
Executing /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine regedit /S C:\windows\Temp\_register-font.reg
Executing /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine64 regedit /S C:\windows\Temp\_register-font.reg
Executing cp /mnt/Games/Games/battlenet/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.IMd7VHlL/_reg_21e53125_3779.reg
Executing /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine regedit /S C:\windows\Temp\_register-font.reg
Executing /home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine64 regedit /S C:\windows\Temp\_register-font.reg
Executing cp /mnt/Games/Games/battlenet/dosdevices/c:/windows/temp/_register-font.reg /tmp/winetricks.IMd7VHlL/_reg_4779f8a8_3779.reg
You opted in, so reporting 'tahoma ' to the winetricks maintainer so he knows which winetricks verbs get used and which don't.  Use --optout to disable future reports.
Monitored process exited.
Initial process has exited (return code: 0)
Exit with return code 0
Started initial process 4803 from /usr/bin/bash -c WINEPREFIX="/mnt/Games/Games/battlenet" "/home/gustavo/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine" "/mnt/Games/Games/battlenet"/drive_c/Battle.net-Setup.exe
Start monitoring process.
Monitored process exited.
Initial process has exited (return code: 136)
All processes have quit
Exit with return code 136

**Comment by strycore** [comment]
Running Overwatch 2 with LoL wine build (lutris-ge-lol)

**Comment by Gustavo17pacheco** [comment]
How do I change it before starting the installation?

**Comment by Gustavo17pacheco** [comment]
Nevermind, I found out. 
![image](https://github.com/lutris/docs/assets/8608735/08520688-ab32-4fbd-9454-f325d3326ff5)

**Comment by strycore** [comment]
the current lutris version has a bug were the wrong wine version can end up being selected. That's more or less fixed now.

**Comment by lockie** [comment]
@strycore I'm using Lutris from git `master`, but still have the 136 return code bug. How do I force it to use the correct version?

**Comment by lockie** [comment]
Sorry for the fuss, I've managed to install BNet after computer reboot (which is kinda weird).
